const PLACEHOLDER = (seed) => `https://picsum.photos/seed/${seed}/600/450`;

const seedItems = [
  {
    name: "Rice & Curry 🍛",
    category: "Main Course",
    priceLkr: 150,
    quantity: 120,
    description: "Steamed rice with seasonal curries.",
    available: true,
    isToday: true,
    photoUrl: PLACEHOLDER("rice-curry"),
    emoji: "🍛",
  },
  {
    name: "Kottu Roti 🥘",
    category: "Main Course",
    priceLkr: 200,
    quantity: 90,
    description: "Chopped roti stir-fried with vegetables.",
    available: true,
    isToday: true,
    photoUrl: PLACEHOLDER("kottu-roti"),
    emoji: "🥘",
  },
  {
    name: "Fried Rice 🍚",
    category: "Main Course",
    priceLkr: 220,
    quantity: 70,
    description: "Egg fried rice with carrots and leeks.",
    available: true,
    isToday: false,
    photoUrl: PLACEHOLDER("fried-rice"),
    emoji: "🍚",
  },
  {
    name: "String Hoppers 🍥",
    category: "Breakfast",
    priceLkr: 120,
    quantity: 100,
    description: "Fresh idiyappam served with kiri hodi.",
    available: true,
    isToday: true,
    photoUrl: PLACEHOLDER("string-hoppers"),
    emoji: "🍥",
  },
  {
    name: "Hoppers 🥞",
    category: "Breakfast",
    priceLkr: 100,
    quantity: 80,
    description: "Crispy bowl-shaped hoppers.",
    available: true,
    isToday: false,
    photoUrl: PLACEHOLDER("hoppers"),
    emoji: "🥞",
  },
  {
    name: "Chicken Curry 🍗",
    category: "Main Course",
    priceLkr: 250,
    quantity: 65,
    description: "Slow-cooked chicken curry.",
    available: true,
    isToday: true,
    photoUrl: PLACEHOLDER("chicken-curry"),
    emoji: "🍗",
  },
  {
    name: "Dhal Curry 🥣",
    category: "Main Course",
    priceLkr: 90,
    quantity: 110,
    description: "Creamy red lentils tempered with curry leaves.",
    available: true,
    isToday: false,
    photoUrl: PLACEHOLDER("dhal-curry"),
    emoji: "🥣",
  },
  {
    name: "Veg Roti 🫓",
    category: "Snacks",
    priceLkr: 80,
    quantity: 140,
    description: "Coconut sambol stuffed roti.",
    available: true,
    isToday: true,
    photoUrl: PLACEHOLDER("veg-roti"),
    emoji: "🫓",
  },
  {
    name: "Fish Bun 🐟",
    category: "Snacks",
    priceLkr: 70,
    quantity: 150,
    description: "Classic bakery fish bun.",
    available: true,
    isToday: false,
    photoUrl: PLACEHOLDER("fish-bun"),
    emoji: "🐟",
  },
  {
    name: "Cutlets 🟠",
    category: "Snacks",
    priceLkr: 60,
    quantity: 160,
    description: "Crispy fish cutlets.",
    available: true,
    isToday: true,
    photoUrl: PLACEHOLDER("cutlets"),
    emoji: "🟠",
  },
  {
    name: "Watalappan 🍮",
    category: "Dessert",
    priceLkr: 140,
    quantity: 55,
    description: "Jaggery coconut custard.",
    available: true,
    isToday: false,
    photoUrl: PLACEHOLDER("watalappan"),
    emoji: "🍮",
  },
  {
    name: "Curd & Treacle 🥛",
    category: "Dessert",
    priceLkr: 160,
    quantity: 60,
    description: "Buffalo curd topped with kitul treacle.",
    available: true,
    isToday: true,
    photoUrl: PLACEHOLDER("curd-treacle"),
    emoji: "🥛",
  },
  {
    name: "Ice Cream 🍦",
    category: "Dessert",
    priceLkr: 180,
    quantity: 75,
    description: "Vanilla ice cream cups.",
    available: true,
    isToday: false,
    photoUrl: PLACEHOLDER("ice-cream"),
    emoji: "🍦",
  },
  {
    name: "Tea ☕",
    category: "Drinks",
    priceLkr: 40,
    quantity: 200,
    description: "Plain black tea.",
    available: true,
    isToday: true,
    photoUrl: PLACEHOLDER("plain-tea"),
    emoji: "☕",
  },
  {
    name: "Coffee ☕",
    category: "Drinks",
    priceLkr: 60,
    quantity: 120,
    description: "Freshly brewed coffee.",
    available: true,
    isToday: false,
    photoUrl: PLACEHOLDER("coffee"),
    emoji: "☕",
  },
  {
    name: "Iced Milo 🧋",
    category: "Drinks",
    priceLkr: 120,
    quantity: 95,
    description: "Chilled Milo with condensed milk.",
    available: true,
    isToday: true,
    photoUrl: PLACEHOLDER("iced-milo"),
    emoji: "🧋",
  },
  {
    name: "Lime Juice 🍋",
    category: "Drinks",
    priceLkr: 90,
    quantity: 100,
    description: "Fresh lime cooler with honey.",
    available: true,
    isToday: false,
    photoUrl: PLACEHOLDER("lime-juice"),
    emoji: "🍋",
  },
  {
    name: "Orange Juice 🍊",
    category: "Drinks",
    priceLkr: 110,
    quantity: 85,
    description: "Fresh orange juice.",
    available: true,
    isToday: false,
    photoUrl: PLACEHOLDER("orange-juice"),
    emoji: "🍊",
  },
  {
    name: "Egg Roti 🥚",
    category: "Snacks",
    priceLkr: 90,
    quantity: 130,
    description: "Roti stuffed with seasoned egg.",
    available: true,
    isToday: false,
    photoUrl: PLACEHOLDER("egg-roti"),
    emoji: "🥚",
  },
  {
    name: "Veg Noodles 🍜",
    category: "Main Course",
    priceLkr: 210,
    quantity: 70,
    description: "Stir-fried noodles with vegetables.",
    available: true,
    isToday: true,
    photoUrl: PLACEHOLDER("veg-noodles"),
    emoji: "🍜",
  },
];

module.exports = seedItems;
